### ISSUE TITLE
Improvement: Create enum/type for valueflows types

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/rea-playspace#101]
example in `Pallet.tsx` 
```
  function pickStyle(type: string) {
    if (type === 'resourceSpecification') return 'resource-specification-pallet-node';
    if (type === 'processSpecification') return 'process-specification-pallet-node';
    if (type === 'agent') return 'agent-pallet-node';
  }
```

we see `type === ...` frequently throughout the project. Would be good to make that safer.

**Comment by adaburrows** [comment]
Fun fact, I just tried out this cool feature of TypeScript in my current codebase and it works quite well:

```ts
/**
 * Create enum of all the possible model types
 */
export type ModelType = keyof typeof ModelBuilder;
```

All we'll need to use going forward is `import { ModelType } from '../data/models/ModelConstructors';`

**Comment by adaburrows** [comment]
In fact, I think I'm just going to do that. We can find other places where it needs to happen and then add it in.

**Comment by adaburrows** [comment]
This actually does point towards needing some better state management in FlowCanvas, since we can't use this there. We just so started with those strings, but that variable is actually a UX state machine variable.

**Comment by adaburrows** [comment]
I created the ModelType enum, but we still need to flesh out the UI state machine. Creating a new task for that.
