### ISSUE TITLE
Improvement: People find having both `resourceQuantity` and `effortQuantity` confusing

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#104]
It is confusing (and annoying once you understand it) to have 2 quantities listed as 2 fields like anything else (fault of VF of course).  I'll work on what UX we might be able to put in those modals to help.

**Comment by fosterlynn** [comment]
I can see 2 options, either of which seems fine to me.  (Other ideas welcome!)

* Probably easiest? Put only one quantity on the flow modals.  We could just call it "quantity" and "unit".  When the flow (commitment or event) is saved, have some logic where if it is action `work` or `use` then save those in `effortQuantity` else save those in `resourceQuantity`.  Don't worry about the (edge) use case for using both of them, for now.
* JS? When the action is chosen, if it is `work` then show the effort fields.  Else if it is `use` then show both sets of fields, like it is now, except it would be better with the effort fields first.  Else show just the resource fields.  Then save them based on where they are, or add logic, whatever works best.

**Comment by fosterlynn** [comment]
After some offline discussion, in response to the request to just say what I think best to happen without making assumptions or cutting corners:

Mostly the second option above: 
* if `work` then show/store effortQuantity fields
* if `use` then show/store effortQuantity fields and resourceQuantity fields
* any other action then show/store resourceQuantity fields

Thinking about any suggested text, especially on `use`....

**Comment by shanedeeodonnell** [comment]
@fosterlynn When a Commitment is created, it locks any Events to that same `action`, which makes sense. The Commitment can then be edited after Events are created. In this case I'm only looking at editing `action`. If the `action` is  edited on a Commitment after an Event is created should:
a) The Commitment action be uneditable at this point
b) Should the Event be automatically updated

**Comment by fosterlynn** [comment]
Good question.  b) won't work, because changing the unit would make the amount be meaningless.  So I guess a) is the way to go.
