### ISSUE TITLE
Improvement: UX for "finish" on commitments and processes

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#105]
Finishing Commitments seem to be the most confusing to users (and higher priority), but finishing processes has some of the same UX going on, and it would be good if they match.

**Commitments:**  
Generally the user trigger for when commitments are marked finished is either when entering an event which they know finishes the commitment, or later when they figure out the commitment is actually finished, either actually done or won't be worked on any more.  Right now this is what it looks like:
![Screenshot from 2022-07-31 13-16-49](https://user-images.githubusercontent.com/3776081/182040146-e4ef9218-b107-4f71-a8b9-23389151a897.png)
It is confusing that it is in the middle of the form.  It is also confusing that it is a button, when you also need to hit Update to make it save.  Although that might just be a bug, since Process does update without a save.  So for this issue, let's assume that it does update by itself.

Suggestions, in order of what might be most appropriate, but any of these would be fine imo.
1. Put a Finish Commitment button on the first modal, that shows both commitment and events.  Maybe either next to the Commitment (i) label or on the bottom line with the other buttons.  Make it a sized button like Done and Cancel.  This would be the least keystrokes.
2. On the Commitment modal, make it a smaller sized button like Update and Cancel, and put it either right by the Commitment label at the top, or with the buttons at the bottom.  I think the top would be best because then it is more clear you can do it without updating also; and every screen size can see it when that modal opens (I have to scroll for the bottom buttons).

(I know I have in the past suggested to put it on the Event modal, but I think since we have that overall page, that would better cover the different user stories and be cleaner, so I didn't include it.)

**Process:**
Nice size button, works great:
![Screenshot from 2022-07-31 13-20-05](https://user-images.githubusercontent.com/3776081/182041047-542f4239-c429-402e-ac20-2601f5ecbe6a.png)

Suggest putting it next to the Process label, or with the other buttons at the bottom.  Make it match the way you end up doing Commitment.

**Comment by fosterlynn** [comment]
Another (add on) idea:  I'm finding that the term "Finish" is also confusing in that it might imply just "I'm finished with entering on this screen" to users, even if it gets moved.  Besides the above, maybe call it "Commitment is finished", "Process is finished" or similar.  (It also seems like an option to just comment it out for dweb, not at all essential for initial learning.)

**Comment by adaburrows** [comment]
> It is confusing that it is in the middle of the form. It is also confusing that it is a button, when you also need to hit Update to make it save. Although that might just be a bug, since Process does update without a save. So for this issue, let's assume that it does update by itself.

Yeah, I agree. Basically, I was having issues with the Shoelace component I wanted to use. It would never actually toggle the state value when I used a toggle switch. So I used a button with two states. It met the requirements of the ticket, though it was terrible UX.

I think you're right. We do need to make this a UX action like update instead of having the field as a form field ordered according to its position in the data type.

**Comment by fosterlynn** [comment]
> (It also seems like an option to just comment it out for dweb, not at all essential for initial learning.)

This would be my current opinion. :)

**Comment by adaburrows** [comment]
I was thinking about this a little today. It seems that the most effective UX would be something like having a checkbox next to the commitment. That way, once someone has finished (most likely by creating a commitment), they can immediately mark it as finished without having to go back into the commitment edit form. It would look something like this:

<img width="673" alt="Finish in top level checkbox 1" src="https://user-images.githubusercontent.com/102320/189043332-9c29c4d4-19f3-4b14-8f83-ced8b2514e34.png">
<img width="673" alt="Finish in top level checkbox 2" src="https://user-images.githubusercontent.com/102320/189043341-f50ad92c-6533-40bb-a037-36291c55db74.png">

**Comment by adaburrows** [comment]
The big question I have about this is when a commitment is completable. Should it be possible to mark it as complete before there are any events? Or should it only be possible after an event is created? (I feel like I asked this once before a long time ago).

**Comment by adaburrows** [comment]
Related conversation: https://github.com/lightningrodlabs/rea-playspace/issues/82#issuecomment-1179797530

**Comment by fosterlynn** [comment]
>The big question I have about this is when a commitment is completable. Should it be possible to mark it as complete before there are any events?

Yes, the user should be able to mark it complete whether or not there are events.  Like it was planned but it just isn't going to happen.  Also irrespective of whether the events add up to the commitment in any way. 

>It seems that the most effective UX would be something like having a checkbox next to the commitment.

Agree, that would be perfect.

**Comment by adaburrows** [comment]
OK, so once we get a better set of UI components, we should make a UI like the ones I drafted above.

The big changes I'd make are shortening the commitment "button", placing the checkmark next to it along with an info button describing what completing a commitment means.

**Comment by adaburrows** [comment]
Writing down my progress for my own memory's sake:
- [x] Removed from inner commitment form.
- [ ] Put checkbox in modal as described.
- [ ] Wire up checkbox to commitment state.

**Comment by adaburrows** [comment]
<img width="566" alt="Screen Shot 2022-09-17 at 01 42 46" src="https://user-images.githubusercontent.com/102320/190848413-4eb993a1-96b7-4cf8-a54c-54fb6badbb60.png">
<img width="568" alt="Screen Shot 2022-09-17 at 01 42 59" src="https://user-images.githubusercontent.com/102320/190848415-174da619-09a2-4026-8dcb-0314bf69321e.png">

**Comment by fosterlynn** [comment]
I'm re-opening this because the Finish button is still on the Process modal.  If nothing else, let's just remove it from where it is.

**Comment by adaburrows** [comment]
Closing, because that should actually be a separate ticket (which I'll make). I realize that you have "commitments and processes" in the title of this. But I should have said that is too large of a scope for this ticket. Processes are completely different scenario from finishing a commitment. What I will suggest, since it's easy enough to do, is that we add a separate button on the bottom of the form that says "Update and Mark as Finished".
