### ISSUE TITLE
Fitting agents into the diagram

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#11]
We haven't had a chance to all talk about this at the same time and place.  But the conclusion some of us had for the diagram is that the nodes should be Processes and Resource Specifications.  The Processes are actual processes.  The Resource Specifications are the ones referenced in the Commitment as `resourceConformsTo`.  So, Resource Specifications can appear multiple times on a diagram, but Processes can't.  

More importantly for this issue, Agents shouldn't be able to be a node.  (This is different than the diagram I drew for Code A, which was more conceptual and not actually a UI.)  And it is true that sometimes an Agent (as `provider` or `receiver`) might be more prominent conceptually, but we decided it is cleaner in lots of ways to always have the same visual configuration everywhere of the resource-related and agent-related data referenced on the commitments.

Since Agents are also something referenced by the Commitment, they can appear more than once on the diagram.  In discussion with @shanedeeodonnell we are thinking that the Agents can be shown as an avatar (circle with picture or initials, or however it is currently done), which Shane said would be fairly easy from the Profile app.  We'd have to eventually do something like that for non-person Agents too, but I think that can be after we get the people working, for demo purposes.

The Agent avatar could be dragged and dropped onto the upper left or upper right side of the Resource Specification, depending on if it is a `provider` or `receiver` on the Commitment.  Or something similar, depending on the technical constraints, let's do what fits with the diagramming tool.  If putting it on the ends of the Commitment line works better, that's another idea.

Something like this, note the Agent is `provider` on inputs, `receiver` on outputs. 

![Screenshot from 2022-05-05 16-20-09](https://user-images.githubusercontent.com/3776081/167027844-5d1f4c9a-44d7-43e9-ae75-a6cfb12dfc5f.png)

We could also put both `provider` and `receiver` on all Commitments, thus having the user define both explicitly.  (Not sure if those can be defined on the form for Commitments?)  But that might be hard since many lines can go into and out of a Process.

Please discuss or ask questions or disagree as needed!

**Comment by fosterlynn** [comment]
>The Agent avatar could be dragged and dropped onto the upper left or upper right side of the Resource Specification, depending on if it is a provider or receiver on the Commitment. 

Alternatively, we could just put provider / receiver dropdown(s) on the Commitment form, and not worry about the drag/drop.  Then this discussion would be just about how to display them once they are entered, and we wouldn't worry about how to visually guide the user on where to drag them to and what it means.

**Comment by fosterlynn** [comment]
The other place an Agent shows up is the Process.inScopeOf.  Probably just non-person agents, but we could discuss.  Perhaps it could be displayed in a similar way to the provider/receiver agent.  Like sitting on top of the process in the middle?

How it gets there (drag and drop, or enter in the process form) is another question.  I think we should decide that for all agents that show up on the canvas, and do it the same way (drag/drop or form).

**Comment by adaburrows** [comment]
Summarizing what Lynn and I just chatted about:
* Agents should **not** be dragged onto the canvas. Instead, the are always properties of other objects.
* Form entry makes the most sense, but we did toss around the idea of having something like slots for us to drag certain things onto.
* Every `Commitment` must have a `provider` and a `receiver`:
  * Input `Commitment::`
    * `provider`: `Agent` who has custody/is responsible for the `ResourceSpecification`/`EconomicResource` or the `Agent` providing the work (in the case of a things with an effort).
    * `receiver`: `Agent` from `Process::inScopeOf`.
  * Output `Commitment::`
    * `provider`: `Agent` from `Process::inScopeOf`.
    * `receiver`: `Agent` who has custody/is responsible for the resulting `ResourceSpecification`/`EconomicResource`.
  * Transfer `Commitment::`
    * `provider`: `Agent` who currently has custody/rights/ownership of the `ResourceSpecification`/`EconomicResource`.
    * `receiver`: `Agent` who will have custody/rights/ownership of the `ResourceSpecification`/`EconomicResource`.
* This means that each `Process` should have an `inScopeOf` `Agent`. We'll likely want to have a reasonable default that can be set up somewhere. However, this leads to another rabbit hole discussion about `Agent`s being in an organization `Agent` scope. Because I think the current user's agent's organization would be the reasonable default. Either that of the user's `Agent` itself.
* Displaying agents:
  * When we display the input side of a `Process`, we can have an avatar of the `Commitment::provider` `Agent` display on the `ResourceSpecification`.
  * When we display the output side of a `Process`, we can have an avatar of the `Commitment::receiver` `Agent` display on the `ResourceSpecification`.
  * When we display the `Process`, we can display the avatar of the `Process::inScopeOf` `Agent`.
  * When we display a transfer, we can have a ["button"](https://reactflow.dev/docs/examples/edges/edge-with-button/) that shows the `Commitment::provider` `Agent` avatar with an arrow pointing to the `Commitment::receiver` agent's avatar.
  * We can actually represent as many things as we want along the edge, but we have to manually compute their position along the path of the edge. This means we could also show the agents as avatars floating on the edge, right beside the ends of the `Commitment` with which they conceptually correspond.

**Comment by fosterlynn** [comment]
Thanks much @adaburrows !  Some continuing discussion:

>Input Commitment::
>    provider: Agent who has custody/is responsible for the ResourceSpecification/EconomicResource or the Agent providing the work (in the case of a things with an effort).

I don't think this means we want to require it to be the agent who has the custody, or is primaryAccountable either.  Actually, thinking about it now, at planning phase it would be a pain, and not very reliable, to figure that out.

>Output Commitment::
 >   receiver: Agent who has custody/is responsible for the resulting ResourceSpecification/EconomicResource.

Same thing.  The receiver would most often (but not always) be the group doing the work together, which would be the process.inScopeOf.

I'm thinking in general, if we can get the inScopeOf agent on the process early, the simplest for process-related commitments might be to default all the providers and receivers to that agent, and let them change as they want.

>Transfer Commitment::
>    provider: Agent who currently has custody/rights/ownership of the ResourceSpecification/EconomicResource.
>    receiver: Agent who will have custody/rights/ownership of the ResourceSpecification/EconomicResource.

Yes, so maybe defaults don't make any sense on transfers, and users should just pick the ones they want.  We might be able to provide some sort of default, but very unreliably.

>This means that each Process should have an inScopeOf Agent. .... another rabbit hole discussion about Agents being in an organization Agent scope. Because I think the current user's agent's organization would be the reasonable default. Either that of the user's Agent itself.

Yes the perennial rabbit hole. :)  Although inScopeOf can be assumed to be an Agent for purposes of this app, we can't really assume or require it is a non-person agent, although the vast majority of the time it will be.  Note that people can belong to more than one organization.  (And, are we even implementing AgentRelationships for the first implementation?)  I don't know that we need a default atm, it isn't that hard to pick one from the agent list (or drag if we decide to do it that way), and there won't be huge numbers of processes.  Trying to keep it simple for the moment.

>When we display a transfer, we can have a ["button"](https://reactflow.dev/docs/examples/edges/edge-with-button/) that shows the Commitment::provider Agent avatar with an arrow pointing to the Commitment::receiver agent's avatar.

Cool.  Or would it be easier to do it just like the process-related commitments, just show the provider agent on the "input" side ResourceSpecification, and show the receiver agent on the "output" side ResourceSpecification, the way you described for processes, except there's just the one line.  I think this might be more clear because it would be all consistent?

cc @shanedeeodonnell

**Comment by adaburrows** [comment]
I'm going to close this out and add specific issues for things not yet done. I think the only thing we don't have a version of in the UI is the "Assign to me" button.
