### ISSUE TITLE
New unit: "one"

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#121]
I figured out how to not bother with special checking on units, now that I've broken the ice on changing labels.

```
,
  'one': new Unit({
    id: 'one',
    name: 'each',
    symbol: 'ea'
  })
```

**Comment by fosterlynn** [comment]
But... I see you are doing that now with `piece`, cool!  Still, we could get this one in when you feel like it, very very low priority.

**Comment by adaburrows** [comment]
I'm throwing this in, just because it's a simple cut and paste. It will show up differently in the ui, because this will use 'ea' as the symbol while 'piece' has it's symbol omitted.

**Comment by adaburrows** [comment]
Already merged.
