### ISSUE TITLE
Improvement: Don't allow scroll to change quantities?

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#123]
Very low priority.  I found several times (in some hours of making flows) that my quantity was oddly lower than what I had entered.  In experimenting briefly, it seems that in some positions, if you scroll in that field, you will affect the quantity.  Probably a feature, but works like a bug for me.  I enter a quantity from the keyboard, then take off with my mouse scroll to get down to the save button, which doesn't show in the modal for me without scrolling.  If it is in the "right" place, it affects the number I entered.

**Comment by adaburrows** [comment]
Yes, I found that to be incredibly annoying. However, there doesn't seem to be an easy way to stop that based on flags for the Shoelace input control, so it'll require swapping out the library or some fun hacking: https://shoelace.style/components/input

I'm honestly learning toward swapping out the library for something a little more generic and customizable. There's a growing number of bugs in our app solely from this UI library alone.

**Comment by fosterlynn** [comment]
Let's think about it after dweb?  Not that big of an issue atm.

**Comment by adaburrows** [comment]
We should just swap out shoelace for some of the scoped web components stuff.

**Comment by adaburrows** [comment]
This doesn't happen anymore.
