### ISSUE TITLE
Bug: On flows, the input of or output of process shows the internal id

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#124]
Should show the process name.

If that is any work at all, I'd suggest we just comment it out for now, it looks basically like a dev debug thing, and seems lower priority to have it there than some other feature work.

**Comment by adaburrows** [comment]
Are you sure you're using the newest version? Anything after v0.0.11 should have labels like this:

<img width="1310" alt="Screen Shot 2022-08-18 at 1 33 15 PM" src="https://user-images.githubusercontent.com/102320/185489460-b2a14997-120f-4fa5-8e52-ab94d2c4ffa7.png">

**Comment by fosterlynn** [comment]
Oops, I wasn't clear.  I'm talking about in the modal
![Screenshot from 2022-08-10 13-15-38](https://user-images.githubusercontent.com/3776081/185510384-723b4d54-1c4b-4561-82b6-5df038387a73.png)
.

**Comment by adaburrows** [comment]
Ah, ok, that's a pretty simple change. I think we already have all the variables present and just need to change one line.

**Comment by shanedeeodonnell** [comment]
fixed https://github.com/lightningrodlabs/rea-playspace/pull/150#pullrequestreview-1104622105
