### ISSUE TITLE
Bug: When multiple items are selected and dragged, a subset of the items have their position set to (0,0)

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#125]
I'm not totally sure I can mentally re-create this, but will try.  Please ask questions; or we can look at my diagram together.  The diagram has UID "NYTL" if you want to take a peek directly.

I've been working on this NYTL diagram.  Just so happened I took screen shots to send to them to get some domain help (I'm psychic :smile: ).  Then I decided to add one thing on.  That involved adding a new resource specification (Raglan Sweater Design). I can't remember if that was when it scrambled, or if I drag n dropped it on the canvas and then it scrambled.  But it looks like that was approximately where I was.  Right before that I created a new process from an older process specification, without problems.

Before (first of 4 screen shots going out to the right, let me know if you want the rest):

![flow1](https://user-images.githubusercontent.com/3776081/184507030-9704f9c8-4906-41be-ab17-346fd1a49bda.png)

After (can also get you more shots of this going out to the right if you want):
![Screenshot from 2022-08-13 13-28-04](https://user-images.githubusercontent.com/3776081/184507045-187b9654-a3b0-4b9e-8c23-41c454e18bdb.png)

I feel like I had done that sequence before in the last few days, but can't be sure.  I know I didn't have every single spec done before I started drawing.

I started the diagram with 0.0.10, now am on 0.0.11, but I think I worked in that at least yesterday, maybe before?  I only have the 0.0.11 one open though.
![Screenshot from 2022-08-13 13-40-38](https://user-images.githubusercontent.com/3776081/184506937-bbee30ff-680b-4ee0-be4b-a210b15e6c47.png)

**Comment by fosterlynn** [comment]
P.S. I'll leave the diagram as it is, in case the state of the data helps you debug.  I have other things I can work on.

**Comment by adaburrows** [comment]
This kind of looks like the positioning bug, issue #40, when you drag and drop multiple items (shift-select, then reposition). Did you ever do that accidentally or on purpose while laying things out?

**Comment by adaburrows** [comment]
The reason I ask (I haven't looked at the data for it), is because in your image, the shadow on the box looks like the cumulative shadows of many boxes on top of each other. If you drag one of those boxes to a new place, are there other boxes underneath it?

**Comment by fosterlynn** [comment]
>Did you ever do that accidentally or on purpose while laying things out?

I'm sure I did do that a couple times when laying things out.  It was a while before it scrambled, but if that is part of how #40 works, then that certainly could be it.  (Forgot about that bug.)

Yes!  In one case (at least), there were boxes stacked up on each other.

If that is it, then I'll just take that feature out of the user doc for now.

**Comment by fosterlynn** [comment]
Closing this, assuming it is actually the multiple delete bug.

**Comment by adaburrows** [comment]
This is still a bug.

**Comment by adaburrows** [comment]
I should say, the issue where multiple items are dragged and they all overlap at (0,0) is still open. See [this example I recorded](https://drive.google.com/file/d/18gCjmeyfvrwiv0uk5snbu_RGc3d4tVZQ/view?usp=sharing).

**Comment by adaburrows** [comment]
Supplanted by #174.
