### ISSUE TITLE
Process data entry

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#13]
Here is the current process form:

![Screenshot from 2022-05-06 09-26-44](https://user-images.githubusercontent.com/3776081/167154445-8872257c-9141-457c-8068-161e2e32bbc8.png)

Suggestions:
* Default the name and note from the ProcessSpecification created on the left, let them change them.
* `inScopeOf` can be a drop down of Agents, I think non-Person agents, although some time we might run into a requirement for people as scope.
* We don't need `finished` on the entry form, the app should default `false` in the data store.
* Let's skip the classifications, for simplicity (everywhere).  Disagreements?
* `basedOn` references the ProcessSpecification, so that can just be saved without asking for it.  For the update form, we could add back in `basedOn` and `finished`.  And/or there could be a different UX for finished, on the canvas itself, later, not needed yet.

**Comment by shanedeeodonnell** [comment]
implemented in [PR #20 ](https://github.com/lightningrodlabs/rea-playspace/pull/20/files)
