### ISSUE TITLE
Bug: screen blanks out when flow deleted

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#134]
Leanne and I have both seen this.  I'm not totally positive about the flow deletion as the only condition, or if it does it every time, haven't paid enough attention.  I will do so and report here with anything learned.  I am logging this issue so we don't forget - if you can't recreate, maybe don't spend a lot of time until we get more info.

You can always get it back with some combination of the back browser button and/or reloading the page.  But it is a bit scary.

**Comment by adaburrows** [comment]
More research is needed. My conductor had its temp dir sandbox deleted while it was running and I got a different error state when I tried deleted multiple nodes and edges in a selection, but the screen did go blank and I did see an error.

**Comment by adaburrows** [comment]
Looking at the error and it looks like theres a simple check we need to do. It's trying to delete something that has already been deleted:
<img width="1680" alt="Screen Shot 2022-09-07 at 15 49 29" src="https://user-images.githubusercontent.com/102320/189014223-12771737-38be-477f-9515-b3e15af516a6.png">
<img width="1680" alt="Screen Shot 2022-09-07 at 15 50 14" src="https://user-images.githubusercontent.com/102320/189014238-e2c7873e-7175-48a5-94b2-c1c66a877d56.png">

**Comment by adaburrows** [comment]
Tangentially related To #23.

**Comment by adaburrows** [comment]
Interesting, the edges get added twice. Adding a simple check to see if the edge still exists.
<img width="1680" alt="Screen Shot 2022-09-11 at 18 32 46" src="https://user-images.githubusercontent.com/102320/189559360-c07e50ae-d4d5-464e-93f2-b09175c3e7dd.png">

**Comment by shanedeeodonnell** [comment]
fixed https://github.com/lightningrodlabs/rea-playspace/pull/149
