### ISSUE TITLE
Feature/Discussion: Improve ability to have different flow directions 

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#135]
This is probably a longer discussion topic for the team, I'm not sure what the best solution is from the UX perspective.

Playspace works great for flows that basically travel in one direction, left to right.  You can create a flow from the right little dot on a node to the left little dot on another node, with the options resource spec to process, process to resource spec, or resource spec to resource spec.

The main use case where this has become a problem is when trying to depict reciprocal flows, where it is more intuitive to see the main flows left to right, and the reciprocal flows right to left.  Simple example, Alice transfers some resource to Bob, Bob transfers a payment to Alice.  Possibly related, #97 .  Another possible use case is circular economy flows.

You can place the nodes for right to left, but it looks like this, depending on placement:
![Screenshot from 2022-08-24 07-04-50](https://user-images.githubusercontent.com/3776081/186414260-e58ceb81-b399-43ad-b778-de3beef58bfa.png)
or
![Screenshot from 2022-08-24 07-05-00](https://user-images.githubusercontent.com/3776081/186414278-7730bce3-b320-40c9-84c6-0be0f61f1df7.png)
.

**Comment by adaburrows** [comment]
Lynn and I chatted about this: We just need to add top and bottom connection dots. Then we need to loose up any restrictions on input or output on them. Then the direction of flow is determined by which object you start from and end at.

**Comment by adaburrows** [comment]
Oh, interesting. I remember the code I wrote doesn't care which direction the arrow goes, I just looked at the actual behavior of the current code and it seems there's some weird directionality being imposed by ReactFlow that I wasn't fully aware of until now. It also impacts where the arrowhead is being drawn even if I start drawing from the right to the left. I'll check what the configuration is around that and see if I can relax it or if there's more in depth changes we'll need to make around ReactFlow.

If I have to change more around the arrow, then that gives us an opportunity to get set up for issue #110 and the fact that the arrowhead seems to have different colors than the line when the line is selected.

**Comment by adaburrows** [comment]
Ok, so I just need to add some code to store the exact handle the edge is being dragged from and to. This is what it currently looks like:
<img width="1010" alt="Screen Shot 2022-09-15 at 01 39 00" src="https://user-images.githubusercontent.com/102320/190357685-afd5e1e7-cbfe-46a7-95a4-6643b70240f7.png">

As you can see, I've also fixed the styling issue around the text sometimes being too big for the nodes themselves.

**Comment by adaburrows** [comment]
<img width="1010" alt="Screen Shot 2022-09-16 at 01 25 05" src="https://user-images.githubusercontent.com/102320/190593573-a7caa1e9-8601-4d46-9d37-403df45165a6.png">
<img width="1009" alt="Screen Shot 2022-09-16 at 01 33 07" src="https://user-images.githubusercontent.com/102320/190594373-640f5076-ac4f-4e06-b2d1-4dddac5073ee.png">
