### ISSUE TITLE
Bug: Event Ledger no longer works

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#137]
I have a playspace with 3 events, all fulfilling commitments.  Nothing shows on the event ledger.  

Release 0.0.15, holochain 0.0.154

**Comment by shanedeeodonnell** [comment]
Hasn't converted to `usePath` yet. Easy fix.

**Comment by shanedeeodonnell** [comment]
fixed https://github.com/lightningrodlabs/rea-playspace/pull/148
