### ISSUE TITLE
Replace Shoelace with a Scoped Web Components library, possibly the same one being used by profiles.

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#140]
Related to issues: #105, #118, #123.

**Comment by shanedeeodonnell** [comment]
https://github.com/holochain-open-dev/profiles/blob/966e9a7f93e637e5a7d9d629adcf110021d55b06/ui/package.json#L52-L53

**Comment by adaburrows** [comment]
I did some digging into this:
* It looks like we don't need the shadow root [polyfill](https://github.com/webcomponents/polyfills/blob/master/packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js). Done. We already don't have it.
* Then we likely need to use something like the [Fast React Wrapper](https://github.com/microsoft/fast/blob/master/packages/utilities/fast-react-wrapper/src/index.ts) which also provides a way to fulfill a ref to the component. [Usage docs](https://www.fast.design/docs/integrations/react/) and a read through the code show it can be used outside of the Fast system.
* Or we can use the [Lit CreateComponent](https://github.com/lit/lit/blob/41ab4c4a72d23f50840a94d9ec6eca7abb993740/packages/labs/react/src/create-component.ts) wrapper which is the default for the Shoelace react wrapper.
* Then we just need to do the [same process Shoelace does to produce a react wrapper](https://github.com/shoelace-style/shoelace/blob/af4d25ee374585bcf8da223bf631082f2a954438/scripts/make-react.js#L39) for any of the [Scoped Elements](https://github.com/scoped-elements) we want to use.

As a side note, it seems the reason why I could use the checkmark from Shoelace, is because it [requires a ref to access its properties](https://github.com/shoelace-style/shoelace/blob/af4d25ee374585bcf8da223bf631082f2a954438/docs/components/checkbox.md#custom-validity). So it may be possible to continue using Shoelace, but scoped.

While I'm looking into this, I should also check why we see:
```
reactive-element.ts:66 Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information.
```

**Comment by adaburrows** [comment]
When ReactiveElements from a specific version of Lit is loaded it appends it's version to the global `reactiveElementVersions`, even if it's a Scoped Elements version:
<img width="329" alt="Screen Shot 2022-09-13 at 13 14 42" src="https://user-images.githubusercontent.com/102320/190000757-d0a9e993-3c3f-462a-b710-e64d8fea708c.png">
But why do we have a version 1.0.1 and 1.3.1?

```
  /lit/2.2.1:
    // ...
    dependencies:
      '@lit/reactive-element': 1.3.1
      lit-element: 3.2.0
      lit-html: 2.2.1
    dev: false
  /@holochain-open-dev/context/0.0.3:
    // ...
    dependencies:
      '@lit/reactive-element': 1.3.1
      lit: 2.2.1
    dev: false
  /@scoped-elements/material-web/0.0.19:
    // ...
    dependencies:
      // '@material/*' these depend on '@material/mwc-base': 0.25.3
      // ...
      lit: 2.2.1
    dev: false
  /@material/mwc-base/0.25.3:
    // ...
    dependencies:
      '@lit/reactive-element': 1.0.0-rc.4
```
Since version 1.0.1 is in the scoped elements it should be fine. I won't worry about that. But the 1.3.1 comes from `@holochain-open-dev/context` which has been deprecated (and archived). We should use `@lit-labs/context` instead. Except we don't use it. It should be removed from our dependencies instead.

**Comment by adaburrows** [comment]
After all that, it turns out we don't really need to replace it with scoped elements, unless we want to start packaging bits of the UX to be used in other applications, but I think we have a lot of UX work to do before that's going to be worthwhile for other people. If I really want to use the material design components, then I'll probably just bring them in scoped. I'm just going to see if I can get the ref to work with issue #105. If it does, I think I can start building better UX around shoelace.

**Comment by adaburrows** [comment]
OK, I think I got the hang of using refs. I think we can keep using Shoelace.
