### ISSUE TITLE
Bug: Event list needs to use event date

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#167]
... instead of create date.  We'll need to do a bit of logic to get one event date per event...

**Comment by adaburrows** [comment]
This is related to #41, where we need to create a taxonomy for dates. Should I assume that it should be XOR between `hasPointInTime` and `hasBeginning`?

**Comment by adaburrows** [comment]
Logic I'm thinking about using:

```ts
const times = [e.hasPointInTime, e.hasBeginning, e.hasEnd, e.created];
const orderingTime = times.find((t) => t && t != '' && t != null);
```

It returns the first value that actually exists.

**Comment by fosterlynn** [comment]
Looks good to me!
