### ISSUE TITLE
Bug: My transferCustody has reticulating splines

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#182]
Not able to create an event that seems like it should be OK.

The context(and the resource list does show 30 lb in that resource owned by Bob's Bakery):
![Screenshot from 2022-10-30 09-36-42](https://user-images.githubusercontent.com/3776081/198884601-48ba6d80-c85c-48e6-bd83-49784e3faf7a.png)

The attempted event:
![Screenshot from 2022-10-30 08-21-39](https://user-images.githubusercontent.com/3776081/198884635-dc167fc2-d1e8-4702-8111-e0ddc91b1580.png)

The result (also tried with a resource created for Bob):

![Screenshot from 2022-10-30 08-21-31](https://user-images.githubusercontent.com/3776081/198884733-ec735a67-fb78-4a02-9451-201665beba32.png)

**Comment by adaburrows** [comment]
That's a bug in the label generation code. It's expecting something that isn't there. Should be simple to fix. Also, "Reticualting" is misspelled...

**Comment by fosterlynn** [comment]
Here's another occurrence, different action:
![Screenshot from 2022-10-30 11-05-28](https://user-images.githubusercontent.com/3776081/198888961-0d8dc9f4-cc0a-4d67-a54d-0f15afb1d41b.png)

**Comment by adaburrows** [comment]
Ah, ok. I must have assumed both EconomicResources would be present in the label generating code.

**Comment by adaburrows** [comment]
Oh, this turned out to be really dumb. I forgot to update the keys the `isTransfer` function checked for when we made the change from hyphenated to unhyphenated keys.
