### ISSUE TITLE
Bug/Improvement: Can't not pick a resource option once I hit the dropdown

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#184]
In creating an event, I picked Create a new resource, then decided not to do that.  Couldn't go back to a blank resource, had to start over.
![Screenshot from 2022-10-30 10-48-32](https://user-images.githubusercontent.com/3776081/198888157-86799e11-89ab-4fca-a6a4-5481417141dc.png)

**Comment by adaburrows** [comment]
Oh, yeah. That's a shoelace thing. We have to provide an option that indicates there isn't a resource.

**Comment by adaburrows** [comment]
This brings up a finer UX point. While the initial state of a dropdown is potentially empty, once it is interacted with, it is no longer empty and never actually had a valid empty state. What should the possible choices be?

* "Create a new EconomicResource"
* "Resource not inventoried by receiver"?

I personally believe that the dropdown should never be empty and that's an invalid state. So we need to fully define what all the value are and when they can be a specific value.

**Comment by adaburrows** [comment]
So the other question is, "What did having it blank mean to you?" because I know it's different from my conception.

**Comment by fosterlynn** [comment]
>So the other question is, "What did having it blank mean to you?"

It meant there isn't one, for whatever reason.

I think that's fairly intuitive to people, but I could certainly be wrong, I'm not a UX expert. (Often there is a * for fields that are required, and not one for optional fields.)  Anyhow, however you do it is fine with me, as long as people don't get trapped in the dropdown.  Should we have a default in this case, and is "not inventoried" a reasonable one?  Or make them hit the field even if it isn't applicable to them?  Up to you.

**Comment by adaburrows** [comment]
OK, I went with your idea of just allowing it to be blank. It's a simple fix and if it becomes an issue later, we can massage it if we see people having issues with it.
