### ISSUE TITLE
Event: Date not coming back

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#198]
Added an event, put a date in it 12/30/2022.  When went back and looked, the date was not in the form.

The date is in the data properly though, because it shows on the event report correctly.

**Comment by adaburrows** [comment]
Did you add in a time or just the default time. I might need to see this on your computer since I can't reproduce it.

**Comment by fosterlynn** [comment]
>Did you add in a time or just the default time. I might need to see this on your computer since I can't reproduce it.

Probably did not put in the time.  I'll do some more testing to properly nail down all the conditions. But that will have to be this afternoon for me.

**Comment by fosterlynn** [comment]
I played with this.  Earlier I do remember I was consistently picking the date, but not the time.  When I thought I saw it put in the right date (different than the create date), I must have been wrong, because the event report doesn't show that as of now.  I just tried one date with an explicit time, and it worked fine.

I'm closing this, it was a bad bug report, sorry!
