### ISSUE TITLE
Event data entry

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#31]
Continuing specing these pieces out, please ask if something doesn't seem right or is unclear!

Economic events can be entered as part of (or all of) fulfilling a commitment, or can be entered without a commitment (because they weren't planned).  

Output events `produce` and `raise` can create a new resource, or can add to an existing resource.  All events may have resource effects, depending on action, one or more resources might be updated.  (A lot of that logic is in hREA, but in the meantime, you'll have to create at least some of it.  Definitions here: https://www.valueflo.ws/concepts/actions/#action-behaviors.  Possible pseudocode here: https://lab.allmende.io/valueflows/valueflows/-/wikis/Application-specification-guidance#event-and-resource-logic.  Or possibly logic in hREA to copy.  Or there are a couple different Elixir backend implementations in different coding styles to possibly copy from, let me know and I'll track them down.)

If there is a commitment, a lot of the following data can be defaulted from the commitment, and the user can just change anything needed.

*   action (atm I think display only, from the commitment, seems like changing this would cause more problems than it is worth)
*   quantities (includes a number and a unit) (default from commitment)
*   a datetime (default to "now") [I'm unclear how many options we want to give on this.  We can start with one time (hasPointInTime) if we want, and know that we may also need a range (hasBeginning + hasEnd)]
*   note (no default)
*   provider (default to the commitment provider)
*   receiver (default to the commitment receiver)
*   resourceInventoriedAs, and possibly toResourceInventoriedAs (depending on action) (could provide dropdown of resources for the ResourceSpecification, with primaryAccountable of the provider on inputs or, receiver on outputs, or for transfers, provider on resourceInventoriedAs and reciever on toResourceInventoriedAs)
* save the inputOf or outputOf, even if the commitment already has that

(We may need to add some of the missing fields if we run into other requirements.)

(We could set some logic, either data driven or hard coded, to govern some of the options by action, for example `work` won't have a resourceInventoriedAs, but let's not start there.)

Note that for an event that is fulfilling a commitment (on the same form for the same arrow), you will also need to create a Fulfillment.  Use the same quantity as on the event for now.

For a new resource if one is created:
* name
* trackingIdentifier (let's use that for lot too if they need it)
* note
* primaryAccountable (set to the event receiver)
* stage (set to the process.basedOn ProcessSpecification if there was one)
* (maybe skip containedIn for now, which also means  we wouldn't be supporting `combine` and `separate`, could discuss)

**Comment by fosterlynn** [comment]
Yesterday we talked about being able to click on the arrow, which now brings up the commitment form, and adding a tab for adding or changing events.  I like this option even more, because it occurred to me that then the user could use basically the same interface to create unplanned events (where there is no commitment).  So if the user draws an arrow, the form could allow entry of commitment data, or event data.  In addition to if an existing arrow is double clicked.

We could experiment with tabs vs placement side-by-side or top-bottom to see what works best for users to recognize visually that they are dealing with both commitment and events, and have options.

**Comment by adaburrows** [comment]
I'm going to make separate issues for the a few of the things addressed in here:

* Improvement: add datetime input to event form
* Improvement: don't copy note from commitment to events (while you're at it, see what else is being copied that shouldn't be)
* Improvement: add ability to make fields copied from a commitment read-only
* Feature: Allow events to fulfill a commitment
* Feature: Add inventory tracking code
* Feature: Resource creation dialog
* Feature: Add full graph traversal features to make color coding the graph easier

**Comment by adaburrows** [comment]
Created all the other issues from this ticket. Closing this one.
