### ISSUE TITLE
Feature: Dropdown only applicable actions

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#32]
If it fits reasonably into that point in the logic (they have just drawn an arrow, are being presented the form), it would be helpful to show only the actions that are available, governed by Action.inputOutput - so either input to a process, output from a process, or a not-process-related action.  Or personally I have no problem hard-coding it if it is easier, I don't know what is involved accessing the temporary backend.

I think this is something that would be quite helpful in understanding (or "feeling") the data structure from the UX.  But I don't want to give it a priority right now - depends on difficulty.

**Comment by adaburrows** [comment]
I believe we have everything we need for this. We just need to filter by `Action.inputOutput` in the modal.

https://github.com/lightningrodlabs/rea-playspace/blob/main/ui/src/data/models/Valueflows/Knowledge.ts#L254

**Comment by shanedeeodonnell** [comment]
fixed https://github.com/lightningrodlabs/rea-playspace/pull/58
