### ISSUE TITLE
Bug: When multiple nodes are moved, some get set to coord (0,0)

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#40]
This is likely because of how we're handling onDrag and our position object. However, I don't have much insight into it besides that.

**Comment by shanedeeodonnell** [comment]
@adaburrows Is this still happening?

**Comment by adaburrows** [comment]
@shanedeeodonnell, I never touched the code around this. But I haven't checked to see if it still happens. It likely does, since we still only use that one variable for position tracking.

**Comment by adaburrows** [comment]
This has been superseded by issue https://github.com/lightningrodlabs/rea-playspace/issues/125
