### ISSUE TITLE
Feature: Add location input to Commitment/Event.

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#42]
Currently, my data structure allows having either an address or a gps coordinate. What do we want the UI to look like?

**Comment by fosterlynn** [comment]
Not answering your question, but a suggestion and status note.  

Right now commitment has atLocation, event has atLocation and toLocation.  My opinion, until hearing more from the users, is that we don't include atLocation at all, this was a dev request without specific user input.  And maybe not even toLocation, until we hear more, that one has definite known requirements in general, but not known requirements for Code A.  (Note if we don't include that, then we don't need `move` action.)

Note: So far, we have a requirement from NYTL for Agent.primaryLocation.  And the discussion on [Agent for hREA](https://github.com/h-REA/hREA/issues/219), was that to keep it simple for now, we would just have people enter the long/lat as a string on primaryLocation.  This is based on Agents being pretty stable, and easy to just enter up front.  I don't actually know what hREA is doing for flow related locations, but we can find out, if we want to get synced up now for fewer changes later.
