### ISSUE TITLE
Feature: see currently selected node

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#61]
Currently the UX does not distinguish between selected and unselected nodes/edges. These states should have a visual cue.

**Comment by shanedeeodonnell** [comment]
An artful use of selected: boolean might do the trick.

https://reactflow.dev/docs/api/nodes/custom-nodes/#passed-prop-types

**Comment by adaburrows** [comment]
When I did this, I actually had to choose a different color scheme. None of the colors I was trying looked good. So I went something relatively bright with high contrasts through the color tetrad.
<img width="1038" alt="Screen Shot 2022-09-11 at 17 31 34" src="https://user-images.githubusercontent.com/102320/189556369-1126471c-7a09-42b2-beed-0b1f7a552098.png">
<img width="1033" alt="Screen Shot 2022-09-11 at 17 31 48" src="https://user-images.githubusercontent.com/102320/189556378-0dc3996e-dcf7-4eb7-b7a8-af82028b6f72.png">
<img width="1033" alt="Screen Shot 2022-09-11 at 17 32 05" src="https://user-images.githubusercontent.com/102320/189556384-62680b49-7e21-4c79-b8ed-0d7e952e4d7e.png">
Not pictured the selection cursor is a complementary yellow color, but the resulting selection rectangle is as below:
<img width="1036" alt="Screen Shot 2022-09-11 at 17 32 23" src="https://user-images.githubusercontent.com/102320/189556390-6208e89e-e17d-4f53-aff8-0f83a5a95376.png">

**Comment by adaburrows** [comment]
Also, if we don't like the colors, I think I can derive some new ones using this kind of tool: https://coolors.co/71bffc-dceed1-aac0aa-736372-a18276

**Comment by adaburrows** [comment]
Ok, felt the palette building bug hit me:
<img width="1019" alt="Screen Shot 2022-09-12 at 01 19 57" src="https://user-images.githubusercontent.com/102320/189606759-1070fc8f-f26b-40ce-b559-35f6e4cbda41.png">
<img width="1021" alt="Screen Shot 2022-09-12 at 01 20 11" src="https://user-images.githubusercontent.com/102320/189606786-b8c543f5-f0db-4819-a76e-3b3eb17c1166.png">
<img width="1024" alt="Screen Shot 2022-09-12 at 01 20 30" src="https://user-images.githubusercontent.com/102320/189606795-c1087664-7f22-401f-bcf7-92f76287fb6f.png">
<img width="693" alt="Screen Shot 2022-09-12 at 01 20 48" src="https://user-images.githubusercontent.com/102320/189606807-99c02623-7b3c-4b75-b592-e75d5f442432.png">
<img width="1024" alt="Screen Shot 2022-09-12 at 01 21 10" src="https://user-images.githubusercontent.com/102320/189606825-b9cb527a-eb7d-4a62-be79-bb2de333703c.png">

**Comment by adaburrows** [comment]
I also have colors for errors and such. I just need to hook into our theming for Shoelace and other components.

**Comment by adaburrows** [comment]
I like these colors better:
<img width="1006" alt="Screen Shot 2022-09-12 at 02 12 21" src="https://user-images.githubusercontent.com/102320/189618756-9159fd95-cc4f-4437-a326-cd4c698af033.png">
<img width="1038" alt="Screen Shot 2022-09-12 at 02 12 33" src="https://user-images.githubusercontent.com/102320/189618691-2b1ac138-9bc4-4dd9-a9ad-74f80ed4d0fd.png">
<img width="1057" alt="Screen Shot 2022-09-12 at 02 15 20" src="https://user-images.githubusercontent.com/102320/189618829-07acdaa6-47ed-48e1-a7d1-7f5aa2f66b67.png">

**Comment by shanedeeodonnell** [comment]
complete https://github.com/lightningrodlabs/rea-playspace/pull/147
