### ISSUE TITLE
Bug: Add blank selections

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#62]
For fields that are optional, there tends not to be a blank option, so when the user accidentally picks one there is no way to get rid of it.  I think all of those should have a blank option at the top of the dropdown.

**Comment by adaburrows** [comment]
Implementation details:

This happens enough that we should create a generic utility function that takes a few parameters to know how to pad the list of options.

**Comment by adaburrows** [comment]
Actually, the shoelace clearable property is good enough. I'm using it. There will be an 'x' to clear fields out.

**Comment by adaburrows** [comment]
This ended up being harder than I wanted it to be for very weird reasons, but mostly my upsert function wasn't overwriting values that it should have. There was also some logic around the measurement input control I built. Now the logic is more robust.
