### ISSUE TITLE
Feature: Label code should summarize information

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#64]
Currently, the label code only shows the commitment (if it exists) or the first event if the commitment doesn't exist.

We need to specify more complete behavior for this. My suggestions are:

* Show the commitment if it exists and there are no events logged.
* Show a summary of the events if there are events logged[1].

The main requirements for summarizing events is [1]: We need to ensure the units are the same across all created flows for any particular edge. We also need to implement the code to sum up all the quantities, but that's easy if the units are the same.

**Comment by fosterlynn** [comment]
>We need to ensure the units are the same across all created flows for any particular edge.

One thought: If the commitment exists when an event is entered, default the commitment unit and don't allow entry.  If no commitment, and if there is an event, default the event unit to further events and don't allow entry.

But if that is too much for right now, I'm good with just making sure all units are the same for events; or even just adding it up without checking units, good enough for now.

>Show the commitment if it exists and there are no events logged.

I think it might be helpful to always show the commitment.  Maybe one line with the commitment info, another line with the event summary.  But again, I'm not wanting to make things too complicated before people even see it, so I'm fine with whatever is easiest.

**Comment by adaburrows** [comment]
Just to make this clear, this depended on #80 and #81.

**Comment by adaburrows** [comment]
I have this in the next PR. However, it needs some TLC to add a custom HTML edge so we can display the label as HTML. I tried my hardest to see if we could work around that, but it would take almost as much work and not be as flexible. So I'll add an issue for that.
