### ISSUE TITLE
Feature: Finish commitment button

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#67]
A great place to put a button to mark a commitment finished would be on the modal that shows both commitment and events.  Maybe put under the commitment, could look like the "Create" buttons, and show up once the commitment has been created?  Maybe "Mark finished"  or just "Finish". It would just set the commitment `finished` to `true`.

[edit] Once finished, the button could change to "Unfinished" or similar, and we could allow them to set `finished` to `false` there.

**Comment by adaburrows** [comment]
Because I haven't refactored the code to make this easier. I'm going to put it in the commitment edit form for now. We can open a new issue to refine it.
