### ISSUE TITLE
Bug: Delete doesn't work

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#68]
I can't get anything to delete, either selected by clicking on, or selecting by shift-dragging a boundary.  I've tried delete key (which I understand is the right method) and backspace key.  I'm on ubuntu v20.04, firefox v102.

If we have OS issues, a delete button on the object or its modal would be fine.

Filing as a bug because I think this works for @adaburrows .

**Comment by adaburrows** [comment]
I was mistaken! I gave you the wrong key press combo. It's the left alt key + backspace.
