### ISSUE TITLE
Feature: Update units of measure

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#69]
I'm opening this so we have a place outside of chat to record somewhat ongoing setting of hard-coded units of measure, so they can be added as needed by users.  (If you'd rather have a new issue for other additions, feel free to close this when complete.)

Here is my attempt at an initial list, will need this to demo to anyone, so is high priority.

```
/**
 * Small selection of units for demo purpose
 */
export const Units = {
  'piece': new Unit({
    id: 'piece',
    name: 'piece',
    symbol: ''
  }),
  'day': new Unit({
    id: 'day',
    name: 'day',
    symbol: 'd'
  }),
  'hour': new Unit({
    id: 'hour',
    name: 'hour',
    symbol: 'h'
  }),
  'minute': new Unit({
    id: 'minute',
    name: 'minute',
    symbol: 'min'
  }),
  'foot-USSurvey': new Unit({
    id: 'foot-USSurvey',
    name: 'foot (US survey)',
    symbol: 'ft'
  }),
  'metre': new Unit({
    id: 'metre',
    name: 'metre',
    symbol: 'm'
  }),
  'centimetre': new Unit({
    id: 'centimetre',
    name: 'centimetre',
    symbol: 'cm'
  }),
  'kilometre': new Unit({
    id: 'kilometre',
    name: 'kilometre',
    symbol: 'km'
  }),
  'mile-USSurvey': new Unit({
    id: 'mile-USSurvey',
    name: 'mile (US survey)',
    symbol: ''
  }),
  'acre-USSurvey': new Unit({
    id: 'acre-USSurvey',
    name: 'acre (US survey)',
    symbol: 'ac'
  }),
  'gallon-US': new Unit({
    id: 'gallon-US',
    name: 'gallon (US)',
    symbol: 'gal'
  }),
  'litre': new Unit({
    id: 'litre',
    name: 'litre',
    symbol: 'l'
  }),
  'gram': new Unit({
    id: 'gram',
    name: 'gram',
    symbol: 'g'
  }),
  'kilogram': new Unit({
    id: 'kilogram',
    name: 'kilogram',
    symbol: 'kg'
  }),
  'tonne': new Unit({
    id: 'tonne',
    name: 'tonne',
    symbol: 't'
  }),
  'cup-USCustomary': new Unit({
    id: 'cup-USCustomary',
    name: 'cup (US customary)',
    symbol: 'cup'
  }),
  'tablespoon-US': new Unit({
    id: 'tablespoon-US',
    name: 'tablespoon (US)',
    symbol: 'tbsp.'
  }),
  'teaspoon-US': new Unit({
    id: 'teaspoon-US',
    name: 'teaspoon (US)',
    symbol: 'tsp.'
  })
}
```

**Comment by fosterlynn** [comment]
NYTL will need this, so I thought I'd reopen the same issue, let me know if you prefer ongoing new issues:
```
,
  'poundAvoirdupois': new Unit({
    id: 'poundAvoirdupois',
    name: 'pound',
    symbol: 'lb'
  })
```
There may be more for them, I contacted but haven't heard back yet.  If we can just throw this in with our next planned release, that would be helpful.

Another note:  Here is another unit that has an even more confusing label in the OM2 spec than the "(US survey)" units: "pound (avoirdupois)".  I unilaterally made it "pound" for temporary sanity, while we figure out how to address this kind of thing in general.  I originally thought we would only have trouble with "one", but there are more.  Options:  See if OM2 is open to more alternate labels, including ones that are possibly not unique.  Or, add our own labels as needed, either in the VF spec formally, or in our maintained list of units from OM2.  Or maybe we'll come upon a better idea.

**Comment by fosterlynn** [comment]
>Avoir du pois: https://en.wikipedia.org/wiki/Avoirdupois_system

Yeah, I'm pretty sure I picked the right pound, but tell me if you think I'm wrong!

And, sorry, but I have another one:
```
,
  'yard-International': new Unit({
    id: 'yard-International',
    name: 'yard (international)',
    symbol: 'yd'
  })
```
Or if we want to call it 'yard', that's OK with me, your call.

**Comment by adaburrows** [comment]
> Yeah, I'm pretty sure I picked the right pound, but tell me if you think I'm wrong! The other one is poundApothecaries.

Yes, you picked the right unit.

**Comment by adaburrows** [comment]
Lets open new tickets going forward.
