### ISSUE TITLE
Bug: Scrolling needs to be aware of screen height

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/rea-playspace#70]
The create/edit views often do scroll to the submit button if the browser height is too narrow.

Desired behaviour: Views should scroll all the way down to reveal the submit button.

**Comment by adaburrows** [comment]
An artful `overflow-y: scroll;` in the container's css may do the trick.

**Comment by shanedeeodonnell** [comment]
done. @adaburrows accidentally fixed this in https://github.com/lightningrodlabs/rea-playspace/pull/86
