### ISSUE TITLE
Improvement: Labels and Label generation code

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#72]
I would like to create a more comprehensive list of how each label should look based on the action of the flow.

Currently, labels are generated based on a bunch of different criteria that isn't very organized and it's hard to understand. Creating template functions with the right language and variables for each part of it would go a long way to helping organize that code. Eventually, this could allow us to have internationalization.

**Comment by fosterlynn** [comment]
I'll work on this and make suggested logic/formatting.

**Comment by fosterlynn** [comment]
What I came up with, ideas to make simpler are welcome.

outputs: action N unit [resource name] for receiver [due date]
use: action N unit (resourceQty) for M unit (effortQty) [resource name] from provider [due date]
work: action N unit by provider [due date]
cite: action [resource name] by provider
other inputs: action N unit [resource name] from provider [due date]
transfers: action N unit [resource name] from provider to receiver [due date]
move, raise, lower: action N unit [resource name] in provider (realistically only events, but no problem if it is there for commitments too, might happen)

Approximate logic off the top of my head, not tested obviously, and pretty rough, just one approach.
```
if action == cite then
    qty = ""
else if action == work then
   qty = effortQuantity (number and unit label)
else if action == use then
    if there is a resourceQuantity then
        qty = resourceQuantity (number and unit label) + " for"
    else qty = ""
    qty = qty + effortQuantity (number and unit label)
else 
    qty = resourceQuantity (number and unit label)
if any qty unit == "piece" (or "one" or whatever we end up doing) then
    the unit part of the quantity = ""
if there is a resource then
    res = resource.name
else
    res = ""
if action == a process output then
    agt = "for " + receiver.name
else if action == work or cite then
    agt = "by " + provider.name
else if action == other inputs then
    agt = "from " + provider.name
else if action == one of the transfers then
    agt = "from " + provider.name + "to " + receiver.name
else (move, raise, lower)
   agt = "in " + provider.name
if a commitment then
   due = "due " + due date
label = action.label + qty + res + agt + due 
```

Something like that can work for commitments and events I think.  Then we could do:
```
"Commitment: " + label + line break
"Fulfilled: " + label  (of the totaled events)
```

**Comment by fosterlynn** [comment]
I've made some edits to the above suggestion, may be more to come.

**Comment by fosterlynn** [comment]
Originally from #74 , moving here per @adaburrows recommendation:

An idea while you are in there on this one: Let's check for "piece" and also for "one", and handle that the same way. People might want to use "one", it is the "right" thing to use actually. Or if you prefer, just check for "one" and let "piece" go through as is, and we'll change the hard-coded unit list.

**Comment by adaburrows** [comment]
@fosterlynn what exactly is the "one" thing? Are we saying that we want to add the "one" unit as well as "piece"? If so, I misunderstood (or never actually fully read that comment). That should be a separate ticket to add that.

**Comment by shanedeeodonnell** [comment]
completed with https://github.com/lightningrodlabs/rea-playspace/pull/113

**Comment by adaburrows** [comment]
Just for posterity's sake, here's a picture:

<img width="738" alt="Screen Shot 2022-08-10 at 16 53 25" src="https://user-images.githubusercontent.com/102320/184042530-47df407d-7597-4a09-bd78-308733381a8e.png">
