### ISSUE TITLE
Bug: Deletions come back

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#73]
I deleted both individual items and multiple select items.  They dutifully go away on the page.  But later (I think when I make some other update so the page redraws) they are back. 

In 0.0.2

**Comment by adaburrows** [comment]
If that happens to be the case, then this isn't actually a bug. I'll close this and create a feature to add signals for changes so multiple people can see changes and aren't working on stale data.

**Comment by fosterlynn** [comment]
I'm working in 0.0.3, and this bug is back.

**Comment by fosterlynn** [comment]
Aha!  Recreated, here are details:

Dragged 2 resource specs and one process on.
Deleted one of the resource specs.
Created a commitment, still OK.
Created a new resource spec. ************** this is the key
Deleted resource spec on the canvas came back.

**Comment by adaburrows** [comment]
Weird, there's no reason I can see for this. I'll look into it.

**Comment by adaburrows** [comment]
Aha! I think we may have fixed this. I'll have to test the new code, but we had a problem with the code for deleting objects.

**Comment by fosterlynn** [comment]
In 0.0.4, what I saw:
* I deleted a couple nodes and a flow (the one that was "weird" in pie-story UID).  
* Went to Event list.
* Went back to Flow page.
* What I deleted was back.
* Did a reload (and maybe more?), they were gone.

**Comment by shanedeeodonnell** [comment]
I found why it wasn't included. It will be fixed with this next PR.

**Comment by adaburrows** [comment]
I just made a branch that has the fix in it along with some other fixes I've been working on. I'm just going to finish up creating summaries of the events and create a PR with all of that. This will hopefully be out mid tomorrow.
