### ISSUE TITLE
Bug: 'undefined' is showing up in label when action is 'use' and 'effortQuantity' is empty.

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#74]
I assume you are trying to just not display the unit on the line label when it is `piece`.  It now is showing the word "undefined" where the unit label would be.

0.0.2

**Comment by adaburrows** [comment]
Actually, are you using something without also specifying an effortQuantity? I noticed that last night while I was working on it.

**Comment by adaburrows** [comment]
Basically, I was too tired and trying to get it done that I didn't notice my label code was requiring both a resourceQuantity and effortQuantity. Without the effortQuantity, that part of the label says undefined.

**Comment by fosterlynn** [comment]
An idea while you are in there on this one:  Let's check for "piece" and also for "one",  and handle that the same way.  People might want to use "one", it is the "right" thing to use actually.  Or if you prefer, just check for "one" and let "piece" go through as is, and we'll change the hard-coded unit list.

I asked awhile ago about a different unit or alt label, but maybe I'll take that up again with OM people, thinking longer term.

**Comment by adaburrows** [comment]
Let's add that to issue #72, since that's the right place to put it. I did just overhaul how we assembled the label strings, I think it makes a little more sense, but will still need some massaging when we get to #72. However, I think the issues are gone with the labels.

**Comment by adaburrows** [comment]
Here's the new code in action:
<img width="1680" alt="Screen Shot 2022-08-02 at 01 50 43" src="https://user-images.githubusercontent.com/102320/182334588-de98497c-8910-49bb-a50e-5356166c07be.png">
