### ISSUE TITLE
Bug: Input commitment from process output didn't show up

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#75]
I have an planned output Resource Specification of Raised Beds coming from a process.  I tried to add a planned input from that to the next process, Plant the Raised Beds.  I filled it in, and saved, but the line does not show up.  I tried more than once, pretty sure I entered it OK.

![Screenshot from 2022-07-07 10-21-55](https://user-images.githubusercontent.com/3776081/177811405-5bcd5206-15da-4e1e-827d-b03892a49a02.png)

If you want to recreate it here, install 0.0.2 with UID "code-a".

**Comment by adaburrows** [comment]
Was anyone else opening and editing things at the same time as you?

**Comment by fosterlynn** [comment]
I can't recreate this any more, closing for now.  We can re-open if it is real.
