### ISSUE TITLE
Feature:  Inventory page

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#76]
I'm seeing the need from a "see how REA works" perspective to have a way to see what events do to resources - create, decrement, increment, nothing.  One easy way to do this is with a separate page for inventory by network.  It could be a separate "tab" like the event list being worked on now.  We have also talked about showing actual resources on the visual graph canvas in some way, but haven't figured out how to do it yet, in a clean way.

Note an inventory page will be a requirement of a lot of groups anyhow.

If we decide to do this as a feature, I can spec it out more concretely.

**Comment by adaburrows** [comment]
Depends on #83 and #84

**Comment by adaburrows** [comment]
I'm closing this because we already have a Resource page with a table of current inventory (#181). We also have ticket #180, which will indicate the actual resource in the graph.
