### ISSUE TITLE
Feature: add signals for changes so multiple people can see changes and aren't working on stale data

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#78]
Currently, we aren't sending signals for changes. This means that if multiple people are working on a plan, each time they make a change they overwrite the version on the DHT with their own local copy. If one person deletes something and another person edits their now stale in-memory copy, they will overwrite the deletion.

**Comment by shanedeeodonnell** [comment]
PR for holochain remote_call portion of the ticket. It's in a good position to interface with a reactive state mgmt piece.
https://github.com/lightningrodlabs/rea-playspace/pull/126

**Comment by adaburrows** [comment]
Done
