### ISSUE TITLE
Improvement: don't copy note from commitment to events

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#80]
while you're at it, see what else is being copied that shouldn't be: https://github.com/lightningrodlabs/rea-playspace/blob/main/ui/src/components/modals/FlowModal.tsx#L115

**Comment by adaburrows** [comment]
From the original ticket:

* action (atm I think display only, from the commitment, seems like changing this would cause more problems than it is worth)
* quantities (includes a number and a unit) (default from commitment)
* a datetime (default to "now") [I'm unclear how many options we want to give on this.  We can start with one time (hasPointInTime) if we want, and know that we may also need a range (hasBeginning + hasEnd)]
* note (no default)
* provider (default to the commitment provider)
* receiver (default to the commitment receiver)
* resourceInventoriedAs, and possibly toResourceInventoriedAs (depending on action) (could provide dropdown of resources for the ResourceSpecification, with primaryAccountable of the provider on inputs or, receiver on outputs, or for transfers, provider on resourceInventoriedAs and receiver on toResourceInventoriedAs)
* save the inputOf or outputOf, even if the commitment already has that

**Comment by adaburrows** [comment]
Just to clarify, do the resourceInventoriedAs and toResourceInventoriedAs dropdowns need to be populated with EconomicResources and not ResourceSpecifications?

**Comment by fosterlynn** [comment]
>Just to clarify, do the resourceInventoriedAs and toResourceInventoriedAs dropdowns need to be populated with EconomicResources and not ResourceSpecifications?

Yes.

**Comment by adaburrows** [comment]
Ok, we don't have those, so I'll just leave a comment for later when I add the accounting code.
