### ISSUE TITLE
Improvement: add ability to make fields copied from a commitment read-only

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#81]
Currently, everything can be changed in an event so that it no longer makes any sense for accounting. This should be fixed. While we're at it, make sure that all events on an edge also match the first flow created on the edge. This will make it possible to create summaries that sum over all the events.

**Comment by adaburrows** [comment]
Should the atLocation and toLocation also have this behavior?

**Comment by fosterlynn** [comment]
>Should the atLocation and toLocation also have this behavior?

I think atLocation could be defaulted (only atLocation exists on commitments).  But both should allow picking a different location.

But NOTE: I don't think hREA will have much in the way of locations in MMR.  No SpatialThing, only an agent long/lat hacked in, nothing for resources.  I could be wrong, we can double check.  But per #94 I think that we should take all resource based locations off for now (on flows and on resources).

**Comment by adaburrows** [comment]
We already have the location information, and we could store it separately until it is properly implemented in hREA. Let us continue discussion on #94.
