### ISSUE TITLE
Feature: Allow events to fulfill a commitment

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#82]
When we create an event, there should be an option to fulfill the commitment. A fulfillment needs to be created and associated with all the right objects.

**Comment by adaburrows** [comment]
From Lynn: Use the same quantity as on the event for now.

**Comment by fosterlynn** [comment]
>When we create an event, there should be an option to fulfill the commitment.

I think more like: When we create an event, if there is a commitment, a fulfillment should also be created.  (Not an option if we know the commitment, which in this UX we will.)

**Comment by adaburrows** [comment]
Ok, so fulfillments should be created even if it doesn't finish or complete the commitment?

**Comment by fosterlynn** [comment]
>Ok, so fulfillments should be created even if it doesn't finish or complete the commitment?

Yes.  One fulfillment covers 1 event and 1 commitment.  So if 5 events fulfill a commitment, that's 5 fulfillments.  (And if 1 event fulfills 5 commitments, that's 5 fulfillments with the event quantity split up.  But you don't have that scenario in playspace.)

**Comment by adaburrows** [comment]
Thank you!

**Comment by adaburrows** [comment]
Is there a UI component to this at all? Or is it just about creating fulfillments in the backend?

**Comment by fosterlynn** [comment]
>Is there a UI component to this at all? Or is it just about creating fulfillments in the backend?

No UI component for this use case, just backend.  If/when we get to something where there are multiple commitments for one event (the only use case I know of is people paying off multiple invoices at one time, like from a statement, in conventional economic practices), then there will possibly be a UI component, or maybe not, maybe it just distributes the payment on the backend, we'll find out.

**Comment by fosterlynn** [comment]
I took the "current sprint" label off of this, because actually we don't need to think about it until we move to hREA.  Until then, I don't think we will have persisted data that anyone will be able to keep anyhow.  It looks to users like it works now because of the UI layer maintaining the association.  Less important than anything that we want for dweb or users playing with it now, anything that makes the UX more clear.

**Comment by adaburrows** [comment]
Merged in PR #161 and released in v.0.0.15.
