### ISSUE TITLE
Feature: Add inventory tracking code

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#83]
Currently, we have no code in place to do any accounting. This means we are not creating or updating  the resource objects when events happen. We will need to do that.

Resources are really truly identified by their full set of parameters, but it's also possible that people won't want to see the full granular view. So we might need an accounting setting option that allows choosing the granularity.

**Comment by adaburrows** [comment]
As a part of this work we should allow choosing the newly created EconomicResources for the `resourceInventoriedAs` and `toResourceInventoriedAs` dropdowns for Events. [See issue #80 for comments related to this]

**Comment by fosterlynn** [comment]
>>Just to clarify, do the resourceInventoriedAs and toResourceInventoriedAs dropdowns need to be populated with EconomicResources and not ResourceSpecifications?

>Correct.

Actually, there is more to this, thinking more now.  Not every event will have an inventoried resource to refer to.  So some events will just carry the resourceConformsTo (ResourceSpecification) and not any resourceInventoriedAs (EconomicResource).  If there is a Commitment, the resourceConformsTo can be carried down from that.  If not, they will need to be able to pick it.

>As a part of this work we should allow choosing the newly created EconomicResources for the resourceInventoriedAs and toResourceInventoriedAs dropdowns for Events.

Just to make sure, you talking about newly created as in a very recent event?  Or newly created as in we are creating it right now with this event?  If the former, yes true.  If the latter, I think the bit of circularity should be just handled behind the scenes.  (The bit of circularity is that if the users want an event to create a resource, then after that resource is created from both the event and resource information, the reference has to go back into the event.resourceInventoriedAs (or .toResourceInventoriedAs).)  But no need to make the user pick it to do that, we should already know it.  I'm assuming that if the user wants to create a resource from an event, they will need to say so, at least in the form of entering the extra resource information explicitly in the UI.  So they should be able to either pick from a list of existing resources or enter info to create a new one, for the kinds of events (actions) that can create new resources.

**Comment by fosterlynn** [comment]
@shanedeeodonnell links to information useful for this (and also #84 and part of #80 which are related).  Basically these 3 issues comprise: UI for creating new resources with an event, UI for updating resources with an event, and the logic that happens on resource creation/updating from events.

https://www.valueflo.ws/concepts/resources/ includes resource specs vs economic resources, and a bunch of other info

https://www.valueflo.ws/concepts/actions/, possibly mostly the behaviors section https://www.valueflo.ws/concepts/actions/#action-behaviors

https://www.valueflo.ws/specification/event-resource/ (pseudocode, one way to do it)

**Comment by fosterlynn** [comment]
>https://www.valueflo.ws/specification/event-resource/ (pseudocode, one way to do it)

This pseudocode is not right any more, due to an issue with "resource effect" vs "accounting effect" vs "onhand effect".  In process of straightening that up here https://lab.allmende.io/valueflows/valueflows/-/merge_requests/706.

**Comment by adaburrows** [comment]
Merged in v0.0.15 with PR #161
