### ISSUE TITLE
Improvement: Agents that cross networks

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#93]
Now, Agents (the REA kind) are limited to one network.  

This includes the person who is the user, who must create a new Profile and join each network as a new REA Person.  We will want a real life person to be able to be 1 Person in any hREA network they belong to, with a separate holochain Profile in each, as currently defined by holochain.  We hope eventually a real life person could be 1 Person in all the holochain apps they are involved with.  And reaching for the stars, a real life person could access apps in holochain and other technical ecosystems, as the same Person.  But back to earth, we do want a Person Agent to be able to join any hREA network as themselves.

This will apply to Organizations and Ecological Agents (name tbd) also.   Each of those Agents should be identified in the same way across networks (hREA networks for now) they participate in.

This moves us in the direction of actual "agent-centric" computing.

**Comment by adaburrows** [comment]
This is a big problem. The [perspect3vism](https://github.com/perspect3vism/agent-language) project seems to use [DIDs](https://w3c.github.io/did-core/) for that.

Also, do you want us to solve this problem independent of hREA? Or do you want us to switch to that? Currently, that would be an upstream issue that would effect us when we switch over.

**Comment by fosterlynn** [comment]
>Also, do you want us to solve this problem independent of hREA?

Definitely not.

>Or do you want us to switch to that?

Assuming you mean hREA, only when it happens anyway (playspace and hREA have talked about it happening after dweb).

Sorry, this was labeled unprioritized to a) keep it for when we need to deal with it, and b) so we don't accidentally design extra blockers in our way for later. I'll close this issue and create another way to keep track of future issues in when I notice them, rather than distracting you all.
