### ISSUE TITLE
Improvement: Date format

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#96]
Dates should be yyyy/mm/dd to be international, and still work for the US.

**Comment by adaburrows** [comment]
I'm having issues with Shoelace's datetime selector anyways. So we'll need to find another one or build our own. Shane and I did talk about moving to more material design components, but that might take some work. On the other hand, maybe figuring out how to use those will sort out some of the warning we're getting around not having a custom component registry polyfill.

**Comment by adaburrows** [comment]
Oh, this is in v0.0.11. -> https://github.com/lightningrodlabs/rea-playspace/blob/v0.0.11/ui/src/components/util.ts#L92
