### ISSUE TITLE
Improvement: Show accountable agent on process

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#98]
In working with Leanne on her koala diagram, she had a general sense of "missing the agents" on the visual canvas.   The only place they are missing is on the processes, although they don't stand out on the flows very much either.  Part of this is that she is working from diagrams she did earlier that kind of started with agents, but then blended them with processes.  But I don't think that is key.

In thinking about New York Textile Lab, the diagrams they did by hand had the agent showing prominently kind of sitting on top of the processes.  On the other hand the Code A garden project doesn't really need them so much, since it is mostly one agent, the garden class where people are working on various processes as part of that organizational agent.

I think this is important for networks that are supply chain networks, or other loose networks where there will be a number of different agents managing different processes.  Less important for plans that are mostly in the scope of one agent, but still it won't hurt for them either.  For example, even the garden project could have the dining hall or others showing up occasionally.

I think that whatever is easiest will be fine, presumably adding the agent name to the process name, maybe like "Forestry Corporation: Log Forest".  Or "Log Forest (Forestry Corporation)".  Whatever you all think.

**Comment by adaburrows** [comment]
Template: `${agent.name}: ${process.name}`

**Comment by adaburrows** [comment]
So, this is more complicated than it seems. However, it's because it uncovered a timing/race condition in our code. I should be able to finish it tomorrow.

**Comment by adaburrows** [comment]
Finally figured out what was going on. I had to convert a few things over to be more like how I wrote the code for the display edges.
