### ISSUE TITLE
Improvement: Make agent list functionality more clear

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#99]
The fact that the agents look like you can drag and drop them is confusing.  It might be enough to just make it a list without any colored shape.  At some point, we may want to get the agent creation off of the left side bar, but let's try making it look different enough first.

**Comment by adaburrows** [comment]
This has been done with v0.0.12. It also seems that issue #129 superseded this, but this was never closed. Closing.

https://github.com/lightningrodlabs/rea-playspace/pull/130
